<div>
    @include('manageBP.components.content-popup.user-manage')
    <x-fullcard>
        @include('manageBP.components.content-manage.Form-Usermanage')
    </x-fullcard>
    <x-fullcard>
        @include('manageBP.components.content-manage.Show-Userdata')
    </x-fullcard>
</div>
